/* Deterministic, browser-only simulation. No real AI, registry, wallet, VC or SHACL engine. */
const $ = id => document.getElementById(id);
const STEPS = [
  {short:'Trigger', title:'An opportunity becomes an event', actor:'Procurement platform', basis:'Event + catalogue', description:'A public buyer needs an energy-efficient renovation service. The event links buyer and supplier services.', heading:'Machine-readable opportunity', bullets:['Fictional buyer publishes the intent and target service.','The service catalogue identifies procurement, company evidence and the supplier wallet.','No agent is allowed to infer a legal procurement route on its own.'], agent:'Identify candidate services and suggest a plan. The service portfolio mode follows a fixed sequence.', control:'Buyer remains responsible for the published need and procedure.'},
  {short:'Requirements', title:'Approve structured requirements', actor:'Public buyer', basis:'COM(2026) 590 · scenario', description:'The buyer agent suggests evidence types and procedure-specific conditions for expert review.', heading:'Requirements proposed for the fictional tender', bullets:['Company registration and an authorised representative.','Tax and social contribution status as of the reference date.','Financial capability and professional qualification.','The buyer publishes only conditions a procurement expert has approved.'], agent:'Propose evidence profiles and flag missing or ambiguous conditions; cannot publish the call.', control:'Human gate: the buyer approves the conditions and publication.'},
  {short:'Discover', title:'The supplier agent finds the tender', actor:'Supplier', basis:'Scoped discovery', description:'A Finnish SME’s agent matches the opportunity against its declared capabilities.', heading:'Opportunity matched to company profile', bullets:['Synthetic Finnish supplier: Aalto Timber Services Oy.','Tender location and evidence requirements are read from the structured notice.','The agent suggests participation and lists required attestations.'], agent:'Search approved procurement feeds and recommend a match; cannot commit the business to bid.', control:'The supplier can decline participation or stop its agent.'},
  {short:'Evidence', title:'Assemble current evidence', actor:'Issuers + authentic sources', basis:'Issuer + status checks', description:'The issuer side supplies synthetic facts; the wallet holds evidence for selective presentation.', heading:'Three distinct responsibilities', bullets:['Authentic source supplies synthetic company and compliance facts.','Issuer applies a versioned profile and supplies a sample credential record.','Status, freshness and trusted issuer checks are separate from the meaning of a field.'], agent:'Coordinate permitted requests and explain a missing record; cannot invent facts or signatures.', control:'Issuer controls what it attests. A simulated failure stops progress here.'},
  {short:'Mandate', title:'Check who may act for the supplier', actor:'Supplier wallet', basis:'Mandate + purpose', description:'The wallet checks representation authority before anything is presented.', heading:'A narrow mandate for this procedure', bullets:['Person: Mira Example; organization: Aalto Timber Services Oy.','Scope: prepare and present eligibility evidence for this tender.','A revoked or insufficient mandate blocks the presentation.'], agent:'Prepare the minimum disclosure request; cannot bypass mandate or approve its own authority.', control:'Human gate: an authorised supplier representative approves disclosure.'},
  {short:'Present', title:'Present an agreed evidence profile', actor:'Wallet → eligibility service', basis:'URI + profile v0.1', description:'Fields are matched to governed identifiers and code lists, not labels in Finnish, Swedish or Dutch.', heading:'Semantic matching across borders', bullets:['National labels are mapped to a shared concept in an approved profile.','The profile fixes date, obligation, status code and required fields.','An unknown mapping is escalated; an LLM translation cannot silently approve equivalence.'], agent:'Find the applicable profile and explain discrepancies; cannot authorise a new semantic mapping.', control:'Human gate: the supplier submits its binding tender after reviewing the disclosure.'},
  {short:'Verify', title:'Run evidence and rule checks', actor:'Eligibility service + verifier', basis:'Deterministic rules', description:'Trust, profile validity and the buyer’s eligibility conditions are evaluated independently.', heading:'Evidence check, then procedure-specific decision support', bullets:['Illustrative checks: issuer trusted; status current; mandate valid; profile mapped.','Tax status is CLEAR as of the reference date. UNKNOWN is never treated as CLEAR.','The result includes an evidence trace and identifies exceptions for human review.'], agent:'Summarise verified results and exceptions. The demo uses fixed templates, no LLM.', control:'The procurement buyer retains responsibility for legal assessment.'},
  {short:'Decision', title:'The buyer reviews the outcome', actor:'Public buyer', basis:'Accountable decision', description:'The buyer receives the rule results and source trace; the award is never made by the agent.', heading:'A reviewable case file', bullets:['Eligibility evidence is separate from tender quality and price.','The buyer considers any legal and qualitative assessments.','A later status change can trigger a new evidence check when required.'], agent:'Prepare a concise case summary; cannot make or sign an award decision.', control:'Human gate: a responsible public buyer makes the consequential decision.'}
];
const COUNTRIES = {
  FI:{name:'Finland',label:'verovelkatilanne',source:'Synthetic Finnish Tax Administration source',code:'FI: CLEAR',buyer:'Finnish municipality'},
  SE:{name:'Sweden',label:'skatteskuldstatus',source:'Synthetic Finnish issuer → Swedish buyer',code:'SE: CLEAR',buyer:'Swedish public buyer'},
  NL:{name:'Netherlands',label:'status belastingschuld',source:'Synthetic Finnish issuer → Dutch buyer',code:'NL: CLEAR',buyer:'Dutch public buyer'}
};
const FAULTS = {
  expired:{at:3,title:'Credential expired',detail:'The synthetic tax credential is past its validity date. Request a new issuance before presentation.'},
  untrusted:{at:3,title:'Issuer not trusted',detail:'The issuer is absent from the simulated trust list. A fresh record alone cannot fix this.'},
  revoked:{at:4,title:'Mandate revoked',detail:'The representative no longer has a valid authorisation for this procedure. Stop disclosure.'},
  unmapped:{at:5,title:'Semantic mapping missing',detail:'The national status field has no approved mapping to the shared profile. Escalate it to semantic governance.'},
  unknown:{at:6,title:'Status unknown',detail:'The source returned NO_INFORMATION. The eligibility rule must not convert that to CLEAR.'}
};
let state={step:0,completed:false,trace:[],run:1};
const currentCountry=()=>COUNTRIES[$('country').value];
const currentFault=()=>FAULTS[$('fault').value];
const mode=()=>document.querySelector('input[name="mode"]:checked').value;
const record=(owner,action,kind='ok')=>state.trace.push({seq:state.trace.length+1,owner,action,kind,step:state.step});
function reset(){state={step:0,completed:false,trace:[],run:state.run+1};record('System',`New synthetic ${currentCountry().name} scenario · ${mode()==='adaptive'?'agent proposed plan':'defined service portfolio'}`);render();}
function resultStatus(key,step){let f=currentFault();if(f&&f.at===step&&((key==='Tax status'&&['expired','unknown','untrusted'].includes($('fault').value))||(key==='Mandate'&&$('fault').value==='revoked')||(key==='Profile mapping'&&$('fault').value==='unmapped')))return 'Issue';return step<=state.step?'Sample OK':'Pending';}
function render(){let n=state.step,s=STEPS[n],f=currentFault(),blocked=f&&f.at===n;
  $('run-number').textContent='#'+String(state.run).padStart(3,'0');$('step-title').textContent=s.title;$('step-description').textContent=s.description;
  $('actor-label').textContent=s.actor;$('basis-label').textContent=s.basis;
  $('stage-badge').textContent=state.completed?'RUN COMPLETE':blocked?'ACTION REQUIRED':n===0?'READY':n===7?'HUMAN REVIEW':'IN PROGRESS';$('stage-badge').classList.toggle('warning',!!blocked||n===7&&!state.completed);
  $('progress').innerHTML=STEPS.map((x,i)=>`<button class="step-tab ${i===n?'active':i<n?'done':''}" type="button" data-step="${i}" ${i>n?'disabled':''} aria-current="${i===n?'step':'false'}"><span class="step-n">0${i+1}</span>${x.short}</button>`).join('');
  $('stage-detail').innerHTML=`<h4>${s.heading}</h4><ul>${s.bullets.map(b=>`<li>${b}</li>`).join('')}</ul>`;
  $('issue-box').textContent=blocked?`${f.title}. ${f.detail} Select a healthy evidence chain or reset to run another case.`:'';
  $('advance').disabled=!!blocked||state.completed;$('advance').textContent=state.completed?'Completed ✓':n===7?'Record human decision →':n===1?'Buyer approves & continues →':n===4?'Approve disclosure →':n===5?'Submit tender →':'Run next step →';$('back').disabled=n===0;
  $('agent-text').textContent=mode()==='adaptive'?s.agent:`A predefined service portfolio fixes this task's position: ${s.short}. Conditions, authority and checks remain the same.`;$('control-text').textContent=s.control;
  $('evidence-list').innerHTML=[['Company identity',2],['Tax status',3],['Social contributions',3],['Mandate',4],['Profile mapping',5]].map(([key,at])=>{let v=resultStatus(key,at);return `<div class="evidence-item"><span>${key}</span><b class="${v==='Issue'?'bad':''}">${n>=at?v:'Pending'}</b></div>`}).join('');
  $('trace').innerHTML=state.trace.map(e=>`<li><time>T+${String(e.seq-1).padStart(2,'0')}</time><span><strong>${e.owner}</strong> · ${e.action}</span></li>`).join('');
  renderSemantics();
}
function advance(){let n=state.step,f=currentFault();if(state.completed||f&&f.at===n)return;
  if(n===7){record('Public buyer','Human review recorded; simulation ended (no real award).','gate');state.completed=true;render();return;}
  const actions=['Event registered; scoped service catalogue loaded.','Procurement expert approved synthetic criteria.','Supplier agent suggested participation; supplier remained in control.','Synthetic records checked: source, issuer, status and profile are distinct.','Representative approved procedure-specific evidence disclosure.','Tender presentation authorised; labels aligned via the approved semantic profile.','Rule check returned an explained, procedure-specific result.'];
  record(STEPS[n].actor,actions[n],[1,4,5].includes(n)?'gate':'ok');state.step=n+1;
  let issue=currentFault();if(issue&&issue.at===state.step)record('Exception control',`${issue.title}: ${issue.detail}`,'issue');
  render();
}
function renderSemantics(){let c=currentCountry(),fault=$('fault').value,concept='urn:demo:semantic:tax-obligation-status',mapped=fault!=='unmapped',status=fault==='unknown'?'NO_INFORMATION':'CLEAR';
  $('mapping-demo').innerHTML=`<div class="mapping-row"><span>Local label</span><strong>${c.label} (${c.name})</strong></div><div class="mapping-row"><span>Common concept</span><strong><code>${mapped?concept:'UNMAPPED · expert review'}</code></strong></div><div class="mapping-row"><span>Value code</span><strong>${status}</strong></div><div class="mapping-row"><span>Profile</span><strong>eligibility-tax-status / demo v0.1 · reference date 2026-09-26</strong></div><div class="mapping-row"><span>Rule</span><strong>${mapped?'Tax status must be CLEAR on the specified date.':'No rule evaluation until the mapping is governed.'}</strong></div>`;
  const payload={'@context':{'demo':'urn:demo:semantic:','taxStatus':'demo:tax-obligation-status'},'type':'IllustrativeEvidence','issuer':c.source,'subject':'Aalto Timber Services Oy','localLabel':c.label,'taxStatus':status,'asOf':'2026-09-26','profile':'eligibility-tax-status/demo-v0.1','mappingApproved':mapped};$('json-preview').textContent=JSON.stringify(payload,null,2);
}
document.addEventListener('click',e=>{let tab=e.target.closest('[data-step]');if(tab){let n=Number(tab.dataset.step);if(n<=state.step){state.step=n;state.completed=false;record('Presenter',`Returned to ${STEPS[n].short} for inspection.`);render();}}});
$('advance').addEventListener('click',advance);$('back').addEventListener('click',()=>{if(state.step>0){state.step--;state.completed=false;record('Presenter',`Returned to ${STEPS[state.step].short} for inspection.`);render();}});
['country','fault'].forEach(id=>$(id).addEventListener('change',reset));document.querySelectorAll('input[name="mode"]').forEach(x=>x.addEventListener('change',reset));$('reset').addEventListener('click',reset);
$('download').addEventListener('click',()=>{let out={disclaimer:'Synthetic browser simulation; no live credentials or legal decision',country:$('country').value,mode:mode(),fault:$('fault').value,completed:state.completed,entries:state.trace};let url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='event-ecosystem-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('copy-json').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('json-preview').textContent);$('copy-json').textContent='Copied ✓';setTimeout(()=>$('copy-json').textContent='Copy JSON',1800)}catch{$('copy-json').textContent='Select text to copy';}});
state.run=0;reset();
